version: '3.3'
services:

  dataiku:
    image: dataiku/dss
    hostname: dataiku
    ports:
      - "10003:10000"
    volumes:
      - ../shared_volume:/shared
      - stack_dataiku:/home/dataiku/dss

networks:
  default:
    external:
      name: data_network

volumes:
  stack_dataiku: